// Copy the Vajra icon set (studio/branding/, regenerated by regen-icons.mjs)
// into the cloned Code-OSS fork. No dependencies - pure file copy. Idempotent;
// build.ps1 re-runs it each compile so an upstream checkout can't drop it.
//
//   node scripts/apply-icons.mjs <vscodeDir>
//
// The bundled Vajra extension's own icon lives in vscode-extension/media/ and is
// carried into the fork by the normal bundle step - not touched here.
import { copyFileSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const brand = join(here, "..", "branding");
const vscodeDir = process.argv[2] || join(here, "..", "vscode");

let n = 0;
const cp = (src, dstRel) => {
  const from = join(brand, src);
  const to = join(vscodeDir, dstRel);
  if (!existsSync(from)) { console.warn(`apply-icons: missing branding/${src} - run regen-icons.mjs`); return; }
  if (!existsSync(dirname(to))) { console.warn(`apply-icons: no target dir for ${dstRel} - skipped`); return; }
  copyFileSync(from, to);
  console.log(`apply-icons: ${dstRel}`);
  n++;
};

cp("code.ico", "resources/win32/code.ico");         // .exe icon (rcedit) + installer + file assoc
cp("code.ico", "resources/win32/default.ico");      // unknown-file-type icon
cp("code_70x70.png", "resources/win32/code_70x70.png");
cp("code_150x150.png", "resources/win32/code_150x150.png");
cp("code.icns", "resources/darwin/code.icns");
cp("code-1024.png", "resources/linux/code.png");    // VS Code ships 1024 and downsizes at packaging
cp("favicon.ico", "resources/server/favicon.ico");
cp("code-192.png", "resources/server/code-192.png");
cp("code-1024.png", "resources/server/code-512.png");

// VisualElementsManifest.xml - Start-menu tile text + colour (not in product.json)
const vem = join(vscodeDir, "resources/win32/VisualElementsManifest.xml");
if (existsSync(vem)) {
  let xml = readFileSync(vem, "utf8");
  const patched = xml
    .replace(/BackgroundColor="#[0-9A-Fa-f]{6}"/, 'BackgroundColor="#12141C"')
    .replace(/ShortDisplayName="[^"]*"/, 'ShortDisplayName="Vajra AI Studio"');
  if (patched !== xml) { writeFileSync(vem, patched); console.log("apply-icons: VisualElementsManifest.xml"); n++; }
}

console.log(n ? `apply-icons: ${n} file(s) updated.` : "apply-icons: nothing to do.");
