import 'gh_api.dart';
import 'nim.dart';

typedef Log = void Function(String line);

class PrResult {
  PrResult(this.url, this.branch, this.summary, this.files);
  final String url;
  final String branch;
  final String summary;
  final List<String> files;
}

/// Standalone task -> pull request. Single-shot: no test loop (CI on the PR
/// does that). Runs entirely from the phone against the GitHub + model APIs.
class GhAgent {
  GhAgent(this.gh, this.model);
  final GhApi gh;
  final ModelClient model;

  static const _maxContextFiles = 8;
  static const _maxFileChars = 16000;

  Future<PrResult> run({
    required String fullName,
    required String baseBranch,
    required String task,
    required Log log,
  }) async {
    log('Reading repository tree…');
    final allPaths = await gh.tree(fullName, baseBranch);
    if (allPaths.isEmpty) throw Exception('empty repository / branch');

    log('Choosing relevant files (${allPaths.length} in tree)…');
    final picked = await _pickFiles(task, allPaths);
    log('→ ${picked.join(", ")}');

    log('Fetching ${picked.length} file(s)…');
    final files = <GhFile>[];
    for (final p in picked) {
      final f = await gh.file(fullName, p, baseBranch);
      if (f != null) files.add(f);
    }

    log('Asking the model for changes…');
    final plan = await _editPlan(task, fullName, files);
    final changes = (plan['changes'] as List).cast<Map<String, dynamic>>();
    if (changes.isEmpty) throw Exception('the model proposed no file changes');

    final branch = _slug(plan['branch']?.toString() ?? 'vajra/${_slug(task)}');
    final commitMsg = plan['commit_message']?.toString() ?? task;
    final summary = plan['summary']?.toString() ?? task;

    log('Creating branch $branch…');
    final baseSha = await gh.headSha(fullName, baseBranch);
    await gh.createBranch(fullName, branch, baseSha);

    final byPath = {for (final f in files) f.path: f.sha};
    final touched = <String>[];
    for (final c in changes) {
      final path = c['path'] as String;
      final content = c['content'] as String;
      log('Committing $path…');
      await gh.putFile(fullName, path, content, commitMsg, branch, byPath[path]);
      touched.add(path);
    }

    log('Opening pull request…');
    final body = '$summary\n\n---\nGenerated by Vajra Mobile for task:\n\n> $task';
    final url = await gh.openPr(fullName, branch, baseBranch, commitMsg, body);
    log('Done.');
    return PrResult(url, branch, summary, touched);
  }

  Future<List<String>> _pickFiles(String task, List<String> paths) async {
    // keep the prompt bounded
    final listing = paths.take(1200).join('\n');
    final reply = await model.chat([
      {
        'role': 'system',
        'content':
            'You select the files most relevant to a coding task. Reply ONLY with a JSON array '
            'of up to $_maxContextFiles repo-relative paths, most relevant first. Paths must be '
            'exactly as they appear in the list.',
      },
      {'role': 'user', 'content': 'Task: $task\n\nRepository files:\n$listing'},
    ], maxTokens: 600);
    final arr = extractJson(reply);
    final set = paths.toSet();
    return [
      for (final x in (arr as List)) x.toString(),
    ].where(set.contains).take(_maxContextFiles).toList();
  }

  Future<Map<String, dynamic>> _editPlan(String task, String repo, List<GhFile> files) async {
    final ctx = StringBuffer();
    for (final f in files) {
      final body = f.content.length > _maxFileChars
          ? '${f.content.substring(0, _maxFileChars)}\n… (truncated)'
          : f.content;
      ctx.writeln('=== FILE: ${f.path} ===');
      ctx.writeln(body);
      ctx.writeln();
    }
    final reply = await model.chat([
      {
        'role': 'system',
        'content': '''You are a senior engineer making a focused change to the repository "$repo".
Return ONLY JSON, no prose, in this shape:
{
  "summary": "one paragraph, what changed and why",
  "branch": "vajra/short-kebab-slug",
  "commit_message": "concise imperative subject line",
  "changes": [ { "path": "relative/path", "content": "FULL new file content" } ]
}
Rules: include the COMPLETE new content of every file you change (not a diff). Only touch
files that need it. Match the existing code style. Keep the change minimal and correct.''',
      },
      {
        'role': 'user',
        'content': 'Task: $task\n\nCurrent files:\n\n${ctx.toString()}',
      },
    ], maxTokens: 8000);
    final obj = extractJson(reply);
    if (obj is! Map) throw Exception('model did not return a JSON object');
    return obj.cast<String, dynamic>();
  }

  static String _slug(String s) {
    var v = s.toLowerCase().replaceAll(RegExp(r'[^a-z0-9/]+'), '-').replaceAll(RegExp(r'-+'), '-');
    v = v.replaceAll(RegExp(r'(^[-/]+)|([-/]+$)'), '');
    if (!v.startsWith('vajra/')) v = 'vajra/$v';
    return v.length > 60 ? v.substring(0, 60).replaceAll(RegExp(r'-+$'), '') : v;
  }
}
