"""All API routers, registered by main.py in this order."""

from core.api.routers import (
    agent,
    approvals,
    assist,
    computer,
    debug,
    files,
    git,
    health,
    lsp,
    memory,
    models,
    osdev,
    projects,
    security,
    setup,
    terminal,
    testing,
)

ALL = [
    health.router,
    setup.router,
    projects.router,
    files.router,
    assist.router,
    lsp.router,
    testing.router,
    memory.router,
    models.router,
    terminal.router,
    debug.router,
    git.router,
    agent.router,
    computer.router,
    osdev.router,
    security.router,
    approvals.router,
]
